[package]
name = "relayd"
version = "0.0.0-dev"
authors = ["Rudder developers <dev@rudder.io>"]
edition = "2018"
description = "Rudder relay component"
readme = "README.md"
homepage = "https://www.rudder.io"
repository = "https://github.com/Normation/rudder"
license = "GPL3"

[[bin]]
name = "rudder-relayd"
path = "src/relayd.rs"

[[bench]]
harness = false
name = "benches"

[dependencies]
bytes = "0.4"
chrono = { version = "0.4", features = ["serde"] }
diesel = { version = "1", default-features = false, features = ["postgres", "chrono", "r2d2"] }
flate2 = { version = "1", default-features = false, features = ["zlib"] }
futures = "0.1"
hex = "0.4"
hyper = { version = "0.12", default-features = false }
inotify = "0.7"
log = "0.4"
md-5 = "0.8"
nom = "5"
openssl = "0.10"
regex = "1"
reqwest = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.8"
structopt = { version = "0.3", default-features = false }
thiserror = "1"
tokio = { version = "0.1", default-features = false, features = ["experimental-tracing"] }
tokio-io = "0.1"
tokio-process = "0.2"
tokio-signal = "0.2"
tokio-threadpool = "0.1"
toml = "0.5"
# Compile dev and release with trace logs enabled
tracing = { version = "0.1", features = ["max_level_trace", "release_max_level_trace"] }
tracing-log = { version = "0.1", default-features = false, features = ["log-tracer"] }
tracing-subscriber = { version = "0.1", default-features = false, features = ["env-filter", "fmt", "tracing-log"] }
warp = { version = "0.1", default-features = false }
humantime = "1"

[dev-dependencies]
criterion = "0.3"
filetime = "0.2"
tempfile = "3"
proptest = "0.9"
